config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :appointments, only: [:index, :show, :edit, :update, :destroy]
  resources :experiences do
    resources :appointments, only: [:new, :create]
    resources :reviews, only: [:new, :create]
  end
  # Define the custom root for my experiences
  get 'my-experiences', to: 'experiences#my_index'
  get 'my_experiences/:id', to: 'experiences#my_experience'

  # Appointments - enums
  resources :appointments, only: [:index, :show, :destroy ]

  get 'confirm_appointment/:id', to: 'appointments#confirm', as: :confirm_appointment
  get 'decline_appointment/:id', to: 'appointments#decline', as: :decline_appointment

  get 'agents-appointments', to: 'appointments#my_agent_appointments'

  # TAGS
  resources :experiences do
    resources :experience_tags, only: [:new, :create]
  end
  # get 'experiences/tags/new', to: 'experience_Tags#adding_tag', as: :adding_tag
end

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Abuelitas is made with <i class="fas fa-heart"></i> in Montreal
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky-top px-3 border-bottom">
  <div class="container-fluid">
  <div style="width:212px">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "abuelitas-favicon.png", style: "width:60px"%>
    <% end %>
</div>
    <%= simple_form_for :search, url: experiences_path, method: :get, defaults: { wrapper: false } do |f| %>
      <div class="search-form-control form-group d-flex">
        <%= f.input :activity_name, placeholder: "Search for an experience", class:"form-control string required", label: false %>
        <span class="input-group-text border-0 padding-0 back" id="search-addon">
          <%= f.button :button, class:"new-btn" do %>
            <i class="fas fa-search"></i>
          <% end %>
        </span>
      </div>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
      <%= link_to "View all experiences", experiences_path, class: "nav-link pe-3" %>
        <% if user_signed_in? %>
          <li class="nav-item active">
          </li>
          <li class="nav-item dropdown">
          <%# <>Welcome <%= current_user.first_name %>
            <%= cl_image_tag(current_user.photo.key, :height=>40, :width=>40, :crop=>"thumb", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }) %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Create Experience", new_experience_path, class: "dropdown-item" %>

              <% if !current_user.experiences.empty? %>
              <%=link_to "My Dashboard", my_experiences_path, class: "dropdown-item" %>
              <% end %>
              <%= link_to "My Appointments", appointments_path, class: "dropdown-item" %>
              <%= link_to "Update Profile", edit_user_registration_path, class: "dropdown-item" %>
              <div class="dropdown-divider"></div>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, status: :see_other, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>