config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :appointments, only: [:index, :show, :edit, :update, :destroy]
  resources :experiences do
    resources :appointments, only: [:new, :create]
    resources :reviews, only: [:new, :create]
  end
  # Define the custom root for my experiences
  get 'my-experiences', to: 'experiences#my_index'
  get 'my_experiences/:id', to: 'experiences#my_experience'

  # Appointments - enums
  resources :appointments, only: [:index, :show, :destroy ]

  get 'confirm_appointment/:id', to: 'appointments#confirm', as: :confirm_appointment
  get 'decline_appointment/:id', to: 'appointments#decline', as: :decline_appointment

  get 'agents-appointments', to: 'appointments#my_agent_appointments'

  # TAGS
  resources :experiences do
    resources :experience_tags, only: [:new, :create]
  end
  # get 'experiences/tags/new', to: 'experience_Tags#adding_tag', as: :adding_tag
end

app/models/experience.rb
class Experience < ApplicationRecord
  has_one_attached :photo
  has_many :reviews, dependent: :destroy
  has_many :appointments

  has_many :experience_tags, dependent: :destroy
  has_many :tags

  accepts_nested_attributes_for :experience_tags, :tags, reject_if: :all_blank, allow_destroy: true

  belongs_to :user
  geocoded_by :address

  validates :grandma_name, presence: true
  validates :activity_name, presence: true
  validates :description, presence: true
  validates :price, presence: true
  validates :address, presence: true
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  before_action :set_experience, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    if params[:search]
      experiences_params = params[:search][:activity_name].downcase
      @experiences = Experience.where("LOWER(activity_name) LIKE ?", "%#{experiences_params}%")
    else
      @experiences = Experience.all
    end
    @markers = @experiences.geocoded.map do |experience|
      {
        lat: experience.latitude,
        lng: experience.longitude,
        info_window: render_to_string(partial: "info_window", locals: {experience: experience}),
        image_url: helpers.asset_url("https://res.cloudinary.com/dg7mx0hnl/image/upload/v1660853532/6_ebqm2m.png")
      }
    end
  end

  def show
    @review = Review.new
    if @experience.geocode.nil?
      latitude = 45.501690
      longitude = -73.567253
    else
      latitude = @experience.geocode[0]
      longitude = @experience.geocode[1]
    end
    @markers = [
      {
        lat: latitude,
        lng: longitude,
        info_window: render_to_string(partial: "info_window", locals: {experience: @experience }),
        image_url: helpers.asset_url("https://res.cloudinary.com/dg7mx0hnl/image/upload/v1660853532/6_ebqm2m.png")
      }
    ]
  end

  def new
    @experience = Experience.new
  end

  def create
    @experience = Experience.new(experience_params)
    @experience.user = current_user
    if @experience.save
      redirect_to experience_path(@experience)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @experience.update(experience_params)
    redirect_to experience_path(@experience)
  end

  def destroy
    @experience.destroy
    redirect_to experiences_path, status: :see_other, notice: "Experience was successfully destroyed."
  end

  def my_index
    # Find all the experiences belonging
    @my_experiences = Experience.where(user_id: current_user.id)
    # Find all the booking requests received - TO be helped on that one
    @my_agents_appointments = current_user.agent_appointments
  end

  private

  def set_experience
    @experience = Experience.find(params[:id])
  end

  def experience_params
    params.require(:experience).permit(:grandma_name, :activity_name, :description, :photo, :price, :address)
  end
end

app/views/experiences/_experience_tag_fields.erb
<div class="nested-fields">
  <%= f.association :tag, collection: Tag.all, include_blank: false, include_hidden: false %>
  <%= link_to_remove_association "remove tag", f %>
</div>

app/views/experiences/_form.html.erb
<%= simple_form_for(experience) do |f| %>
  <H2>Tags</H2>
  <div id="tags">
    <%= f.simple_fields_for :experience_tags do |tag| %>
      <%= render 'experience_tag_fields', :f => tag %>
    <% end %>
    <div class="links">
      <%= link_to_add_association 'add tag', f, :experience_tags, partial: 'experience_tag_fields' %>

    </div>
  </div>
  <H2>EXPERIENCEEEEE</H2>
  <%= f.input :grandma_name %>
  <%= f.input :activity_name %>
  <%= f.input :description %>
  <%= f.input :price %>
  <%= f.input :address %>
  <%= f.input :photo, as: :file %>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/experiences/_info_window.html.erb
<h2><%= experience.activity_name %> with <%= experience.grandma_name %></h2>
<%= link_to "Learn More", experience_path(experience), class: "btn btn-outline text-center" %>

app/views/experiences/edit.html.erb
<h1>Editing experience</h1>

<%= render "form", experience: @experience %>

app/views/experiences/index.html.erb
<div class="container py-5 border-bottom">
  <h1 class="text-center pb-3">Find an Experience</h1>
    <div class="container">
      <div class="row">
        <% @experiences.each do |experience| %>
          <div class="col p-3">
            <div class="card" style="width: 18rem;">
             <% if experience.photo.attached? %>
              <%= cl_image_tag experience.photo.key, class: "card-img-top" %>
                <% else %>
              <img src= <%= experience.images %> >
                <% end %>
                <div class="card-body">
                  <h5 class="card-title"><%= experience.activity_name %> with <%= experience.grandma_name.first(25) %></h5>
                  <p class="card-text"><%= experience.description.first(100) %>...</p>
                  <p class="card-text"><strong>$<%= experience.price %></strong></p>
                  <%= link_to "Learn More", experience_path(experience), class: "btn btn-outline text-center d-flex justify-content-evenly" %>
                </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
</div>
<div class="container py-5">
  <div style="width: 100%; height: 600px;"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
  </div>
</div>

app/views/experiences/my_index.html.erb
      <div class="container">
    <h1 class="text-center my-3">My experiences listed</h1>
            <%= link_to "Add A Experience", new_experience_path, class: "btn btn-flat"%>
            <div class="row">
              <% @my_experiences.each do |experience| %>
                <div class="col p-3">
                  <div class="card" style="width: 18rem;">
                  <% if experience.photo.attached? %>
                    <%= cl_image_tag experience.photo.key, class: "card-img-top" %>
                      <% else %>
                    <img src="https://res.cloudinary.com/dg7mx0hnl/image/upload/v1660663917/cdc-F98Mv9O6LfI-unsplash_kqthfz.jpg">
                      <% end %>
                      <div class="card-body">
                        <h5 class="card-title">Learn <%= experience.activity_name %> with <%= experience.grandma_name %></h5>
                        <p class="card-text"><%= experience.description %></p>
                        <p class="card-text">Price: $<%= experience.price %></p>
                        <%= link_to "See more", experience_path(experience), class: "btn" %>
                      </div>
                  </div>
                </div>
              <% end %>
            </div>


      <h1 class="text-center my-3">My Appointment requests</h1>
        <div class="row">
            <% @my_agents_appointments.each do |appointment| %>
            <div class="col-6">
                <div class="card-trip mt-6 mb-6 pb-3">
                  <%= cl_image_tag appointment.experience.photo.key %>
                <div class="card-trip-infos align-items-center">
                  <div>
                    <div>
                      <h5 class="card-title mb-3"><%= appointment.experience.activity_name %> with <%= appointment.experience.grandma_name%></h5>
                      <p class="card-text mb-3"><%= appointment.experience.description %></p>
                    </div>
                    <% if appointment.Pending? %>
                      <%= link_to "Confirm request", confirm_appointment_path(appointment, status: 1), class: "btn" %>
                      <%= link_to "Decline request", decline_appointment_path(appointment, status: 2), class: "btn"%>
                      <% end %>
                  </div>
                  <div>
                    <%# to be replaced with the user client image%>
                    <%# <%= cl_image_tag appointment.experience.photo.key, class: "card-img-top card-trip-user avatar-bordered rounded-circle" %>
                    <% if appointment.Pending? %>
                          <p class="btn-blue mb-3"><%= appointment.status %></p>
                    <% elsif appointment.Confirmed? %>
                          <p class="btn-green mb-3"><%= appointment.status %></p>
                    <% elsif appointment.Declined? %>
                          <p class="btn-red mb-3"><%= appointment.status %></p>
                    <% end %>
                    <h2 class="card-trip-pricing mb-3 h1">$<%= appointment.experience.price %></h2>
                  </div>
                </div>
            </div>
        </div>
              <% end %>
    </div>

app/views/experiences/new.html.erb
<div class="container py-5">
  <h1 class="pb-3">Create a new experience</h1>
  <%= render "form", experience: @experience %>
</div>

app/views/experiences/show.html.erb
<div class="experience-title">
  <h1 class="text-center"><%= @experience.activity_name %> with <%= @experience.grandma_name %></h1>
  <h4 class="text-center pt-3">Hosted by <%= @experience.user.first_name %> <%= @experience.user.last_name %></h4>
</div>

<div class="card-product-show">
  <% if @experience.photo.attached? %>
    <%= cl_image_tag @experience.photo.key, class: "card-img-top" %>
  <% else %>
    <img src= <%= @experience.images %> >
  <% end %>
  <div class="card-product-show-infos">
    <p><%= @experience.description %></p>
    <p><strong>$<%= @experience.price %></strong></p>
    <p>Available everyday of the week</p>
    <div class="">
      <% if @experience.user == current_user %>
        <p><%= link_to "Delete this experience", @experience, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-outline text-center" %></p>
        <%= link_to "Back to All My Experiences", my_experiences_path, class: "btn btn-outline text-center" %>
        <%= link_to "Edit this experience", edit_experience_path, class: "btn btn-outline text-center" %>
      <% else %>
        <%= link_to "Book this experience", new_experience_appointment_path(@experience), class: "btn btn-outline text-center" %>
      <% end %>
    </div>
  </div>
</div>

<div class="map">
  <h2 class="map-title text-center pb-5">This experience takes place at <%= @experience.address %></h2>
  <div style="width: 100%; height: 600px;"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
</div>

<div class="bg-white text-center border-top">
  <div class="container pb-5">
  <% if !@experience.reviews.empty?%>
    <h2 class="py-3">Reviews</h2>
  <% end %>
      <div class="list-group">
        <% @experience.reviews.each do |review| %>
          <li class="list-group-item">
            <small>
              <% count = 0 %>
              <% 5.times do %>
                <% if review.rating > count %>
                  <i class="fa-solid fa-star"></i>
                <% else %>
                  <i class="fa-regular fa-star"></i>
                <% end %>
                  <% count += 1 %>
              <% end %>
            </small>
            <p>
              <%= review.content %><br>
              - <%= review.user.first_name %> <%= review.user.last_name %>
            </p>
          </li>
        <% end %>
      </div>
  </div>
</div>