config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :appointments, only: [:index, :show, :edit, :update, :destroy]
  resources :experiences do
    resources :appointments, only: [:new, :create]
    resources :reviews, only: [:new, :create]
  end
  # Define the custom root for my experiences
  get 'my-experiences', to: 'experiences#my_index'
  get 'my_experiences/:id', to: 'experiences#my_experience'

  # Appointments - enums
  resources :appointments, only: [:index, :show, :destroy ]

  get 'confirm_appointment/:id', to: 'appointments#confirm', as: :confirm_appointment
  get 'decline_appointment/:id', to: 'appointments#decline', as: :decline_appointment

  get 'agents-appointments', to: 'appointments#my_agent_appointments'

  # TAGS
  resources :experiences do
    resources :experience_tags, only: [:new, :create]
  end
  # get 'experiences/tags/new', to: 'experience_Tags#adding_tag', as: :adding_tag
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user
  belongs_to :experience

  validates :date, presence: true

  enum status: {
    Pending: 0,
    Confirmed: 1,
    Declined: 2
  }
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController

  def new
    @appointment = Appointment.new
    @experience = Experience.find(params[:experience_id])
  end

  def create
    @experience = Experience.find(params[:experience_id]).id
    @user = current_user.id
    @appointment = Appointment.new(appointment_params)
    @appointment.user_id = @user
    @appointment.experience_id = @experience

    if @appointment.save
      redirect_to appointments_path
    else
      render 'appointments/new', status: :unprocessable_entity
    end
  end

  def index
    @my_appointments = Appointment.where(user_id: current_user.id)
    @experience = Experience.where(params[:experience_id])
  end

  def show
    @appointment = Appointment.find(params[:id])
    @experience = @appointment.experience
  end

  def confirm
    @appointment = Appointment.find(params[:id])
    @appointment.Confirmed!
    redirect_to my_experiences_path
  end

  def decline
    @appointment = Appointment.find(params[:id])
    @appointment.Declined!
    redirect_to my_experiences_path, status: :see_other
  end

  def edit
    @appointment = Appointment.find(params[:id])
  end

  def update
    @appointment = Appointment.find(params[:id])
    @appointment.update(appointment_params)
    redirect_to appointments_path
  end

  def destroy
    @appointment = Appointment.find(params[:id])
    @appointment.destroy
    redirect_to appointments_path, status: :see_other, notice: "Appointment was cancelled"
  end

  def my_agent_appointments
    # Find all the experiences belonging
    # Trying to find the appointment.experience.user_id to check if it match current_user
    @my_agents_appointments = current_user.agent_appointments
  end

  private

  def appointment_params
    params.require(:appointment).permit(:date)
  end
end

app/views/appointments/_form.html.erb
<%= simple_form_for @appointment do |f| %>
  <%= f.input :date, html5: true %>
  <div class="text-center pt-5">
    <%= f.submit class: 'btn' %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<div class="container py-5">
  <h1 class="text-center">Change your appointment</h1>
  <%= render "form", appointment: @appointment %>
</div>

app/views/appointments/index.html.erb
<div class="container py-5">
  <h1 class="text-center pb-3">My appointments</h1>
  <br>
  <br>
  <% if @my_appointments.empty? %>
    <p class="text-center">Dear <strong><%= current_user.first_name %></strong>, you do not have any scheduled appointment at the moment.</p>
  <% end %>
  <div class="container">

    <div class="row">
      <% @my_appointments.each do |appointment| %>
        <div class="col p-3">
          <div class="card" style="width: 18rem;">
          <% if appointment.experience.photo.attached? %>
            <%= cl_image_tag appointment.experience.photo.key, class: "card-img-top" %>
              <% else %>
            <img src= <%= appointment.experience.images %> >
              <% end %>
              <div class="card-body">
                <h5 class="card-title"><%= appointment.experience.activity_name %> with <%= appointment.experience.grandma_name%></h5>
                <p class="card-text">Date: <%= appointment.date %></p>
                <div class="mt-2 d-block align-items-center justify-content-evenly flex-direction-column">
                <% if Date.today < appointment.date%>
                  <% if appointment.Pending? %>
                    <p class="btn-blue"><%= appointment.status %></p>
                  <% elsif appointment.Confirmed? %>
                    <p class="btn-green"><%= appointment.status %></p>
                  <% elsif appointment.Declined? %>
                        <p class="btn-red"><%= appointment.status %></p>
                  <% end %>
                <% end %>
                  <%# <p class="card-text">Hosted by: <%= appointment.user.first_name</p>  %>
                  <% if Date.today > appointment.date %>
                    <%= link_to "Review", new_experience_review_path(appointment.experience), class: "btn flex-direction: column;" %>
                  <% else %>

                  <%= link_to "Edit", edit_appointment_path(appointment), class: "d-block mt-3" %><br>
                  <%= link_to "Cancel", appointment_path(appointment), class: "d-block", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
                  <% end %>
                </div>
              </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/appointments/my_agent_appointments.html.erb
<%# Not used atm %>
<div class="container py-5">
  <h1 class="text-center pb-3">My agent appointments</h1>
    <div class="container">
      <div class="row">
        <% @my_agents_appointments.each do |appointment| %>
          <div class="col p-3">
            <div class="card" style="width: 18rem;">
             <% if appointment.experience.photo.attached? %>
              <%= cl_image_tag appointment.experience.photo.key, class: "card-img-top" %>
                <% else %>
              <img src="https://res.cloudinary.com/dg7mx0hnl/image/upload/v1660663917/cdc-F98Mv9O6LfI-unsplash_kqthfz.jpg">
                <% end %>
                <div class="card-body">
                  <h5 class="card-title"><%= appointment.experience.activity_name %> with <%= appointment.experience.grandma_name%></h5>
                  <p class="card-text">Scheduled for: <%= appointment.date %></p>
                  <p class="card-text">Hosted by: <%= appointment.user.first_name %> <%= appointment.user.last_name %></p>
                  <% if Date.today > appointment.date %>
                    <%= link_to "Review this experience", new_experience_review_path(appointment.experience), class: "btn btn-outline text-center" %>
                  <% else %>
                  <%= link_to "Edit appointment", edit_appointment_path(appointment) %><br>
                  <%= link_to "Cancel appointment", appointment_path(appointment), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
                  <% end %>
                </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
</div>

app/views/appointments/new.html.erb
<div class="container py-5">
  <h1 class="text-center py-5">Schedule an appointment</h1>
    <%= simple_form_for [@experience, @appointment] do |f| %>
      <div class="d-flex text-center" style="justify-content: center">
      <%= f.input :date, html5: true %>
      </div>
      <div class="text-center pt-5">
        <%= f.submit class: 'btn' %>
      </div>
    <% end %>
</div>

app/views/appointments/show.html.erb
<%# NOT USED - TO BE UNPLUGGED? %>

<h2>Experience Details</h2>
            <p><%= @appointment.experience.activity_name %></p>
            <p><%= @appointment.experience.description%></p>
          <h3> Dates </h3>
            <p>From: <strong><%= @appointment.start_time %></strong></p>
            <p>Until: <strong><%= @appointment.end_time %></strong></p>
          <h3> Total Price </h3>
            <p> $<%= @appointment.experience.price %> CAD</p>
        </div>
        <div class="col-6  d-flex flex-column justify-content-center align-items-center ">
          <h3>Status of the Request</h3>
        <%= @appointment.status %>

  <div class="row justify-content-center ">
    <div class="col-12 d-flex justify-content-around m-5">
      <% if current_user == @appointment.user %>
          <%= link_to "Cancel appointment", appointment_path(@appointment), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>

        <% else %>
          <%= link_to "Approve request", appointment_confirmed_path(@appointment), class: "btn btn-gradient" %>
          <%= link_to "Decline request", appointment_declined_path(@appointment), class: "btn btn-gradient"%>
        <% end %>
    </div>
  </div>

  <div class="row justify-content-center  ">
    <div class="col-12 d-flex justify-content-center m-3">
      <% if current_user == @appointment.user %>
          <%= link_to "Back to All experiences", experiences_path, class: "btn" %>
        <% else %>
          <%= link_to "Back to my experiences", my_experiences_path, class: "btn"  %>
        <% end %>
    </div>
  </div>
</div>